name: 'Setup minikube'
description: 'Setup minikube'
author: 'Juraci Paixão Kröhling'
inputs: 
  minikube-version:
    description: 'The minikube version to download. Example: v1.3.1'
    default: 'v1.3.1'
runs:
  using: 'node12'
  main: 'lib/main.js'
